name = "ggsbotrs"
workers_dev = true
compatibility_date = "2026-04-14"

main = "build/index.js"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[assets]
directory = "./dist"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
