name = "ggsbotrs"
workers_dev = true
compatibility_date = "2026-04-14"

main = "build/index.js"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[assets]
directory = "./dist"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
