name = "ggsbotrs"
workers_dev = true
compatibility_date = "2026-04-14"

main = "build/index.js"

[[kv_namespaces]]
binding = "ggsbotkv"
id = "c1c5302906b04ad1af9c6f87b80f1367"

[triggers]
crons = [
    "0 * * * *"
]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[assets]
directory = "./dist"

[vars]
WORKER_ENV = "production"
DISCORD_DEVELOPER_ID = "778017089230209045"

[env.production.vars]
WORKER_ENV = "production"
DISCORD_DEVELOPER_ID = "778017089230209045"

[env.local.vars]
WORKER_ENV = "dev"
DISCORD_DEVELOPER_ID = "778017089230209045"

[version_metadata]
binding = "metadata"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
