name = "ggsbotrs"
workers_dev = true
compatibility_date = "2026-04-14"

main = "build/index.js"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[assets]
directory = "./src/assets"

#[[durable_objects.bindings]]
#name = "gateway"
#class_name = "DiscordGateway"

#[exports.DiscordGateway]
#type = "durable-object"
#storage = "sqlite"

#[[migrations]]
#tag = "v2"
#new_sqlite_classes = ["DiscordGateway"]

[[migrations]]
tag = "v3"

[version_metadata]
binding = "metadata"

[vars]
WORKER_ENV = "production"
DISCORD_DEVELOPER_ID = "778017089230209045"
DISCORD_BOT_APPLICATION_ID = "1493638725488476311"
WORKER_METADATA_BINDING = "metadata"
WORKER_GATEWAY_DO_BINDING = "gateway"

[env.production.vars]
WORKER_ENV = "production"
DISCORD_DEVELOPER_ID = "778017089230209045"
DISCORD_BOT_APPLICATION_ID = "1493638725488476311"
WORKER_METADATA_BINDING = "metadata"
WORKER_GATEWAY_DO_BINDING = "gateway"

[env.local.vars]
WORKER_ENV = "dev"
DISCORD_DEVELOPER_ID = "778017089230209045"
DISCORD_BOT_APPLICATION_ID = "1493638725488476311"
WORKER_METADATA_BINDING = "metadata"
WORKER_GATEWAY_DO_BINDING = "gateway"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
