architecture-beta
    group ext(cloud)[Discord API]
    service discord_gateway(internet)[Discord Gateway] in ext
    service discord_interaction(internet)[Discord Interaction] in ext

    group ggsbot(internet)[GGsBot Discord Bot]

    group edge(cloud)[Serverless Cloudflare Network] in ggsbot
    service worker(server)[Worker] in edge
    service tasks_queue(disk)[Tasks Queue] in edge
    service gateway_queue(disk)[Gateway Queue] in edge

    group server(server)[Gateway Server] in ggsbot
    service gateway(server)[WS to HTTP] in server

    discord_gateway:R <-[Websocket]-> L:gateway
    discord_interaction:R <--> L:worker

    gateway:T --> B:worker
    gateway:L --> B:gateway_queue

    gateway_queue:L --> R:worker
    tasks_queue:L <--> T:worker